import numpy as np
from scipy.io import wavfile
import soundfile as sf
from pathlib import Path

SAMPLE_RATE = 44100
DURATION = 30  # seconds
NUM_SAMPLES = SAMPLE_RATE * DURATION
OUTPUT_DIR = Path.home() / "Documents" / "noise"


def generate_white_noise(n_samples, n_channels=2):
    """White noise: flat power spectrum across all frequencies."""
    return np.random.uniform(-1, 1, (n_samples, n_channels)).astype(np.float32)


def generate_pink_noise(n_samples, n_channels=2):
    """Pink noise (1/f): power decreases 3 dB per octave.
    Generated via frequency-domain filtering."""
    white = np.random.uniform(-1, 1, (n_samples, n_channels)).astype(np.float64)

    fft_len = n_samples
    freq = np.fft.rfftfreq(fft_len, d=1.0 / SAMPLE_RATE)

    # Avoid division by zero at DC
    freq[0] = freq[1]

    pink_filter = 1.0 / np.sqrt(freq)
    pink_filter = pink_filter.astype(np.float64)

    pink = np.empty_like(white)
    for ch in range(n_channels):
        fft = np.fft.rfft(white[:, ch])
        fft *= pink_filter
        pink[:, ch] = np.fft.irfft(fft, n=n_samples)

    # Normalize to [-1, 1]
    max_val = np.max(np.abs(pink))
    if max_val > 0:
        pink /= max_val
    return pink.astype(np.float32)


def generate_brown_noise(n_samples, n_channels=2):
    """Brown noise (1/f^2): power decreases 6 dB per octave.
    Generated by cumulative sum (integration) of white noise."""
    white = np.random.uniform(-0.1, 0.1, (n_samples, n_channels)).astype(np.float64)

    brown = np.cumsum(white, axis=0)

    # Normalize to [-1, 1]
    max_val = np.max(np.abs(brown))
    if max_val > 0:
        brown /= max_val
    return brown.astype(np.float32)


def save_wav(path, data, bit_depth=24):
    """Save as high-quality WAV."""
    subtype_map = {16: "PCM_16", 24: "PCM_24", 32: "PCM_32"}
    sf.write(str(path), data, SAMPLE_RATE, subtype=subtype_map.get(bit_depth, "PCM_24"))


def save_flac(path, data, bit_depth=24):
    """Save as FLAC."""
    sf.write(str(path), data, SAMPLE_RATE, format="FLAC", subtype=f"PCM_{bit_depth}")


def main():
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    noises = {
        "brown": generate_brown_noise,
        "white": generate_white_noise,
        "pink": generate_pink_noise,
    }

    for name, generator in noises.items():
        print(f"Generating {name} noise ({NUM_SAMPLES} samples, {SAMPLE_RATE} Hz)...")
        stereo = generator(NUM_SAMPLES, n_channels=2)
        mono = np.mean(stereo, axis=1, keepdims=True)

        wav_path = OUTPUT_DIR / f"{name}_noise.wav"
        flac_path = OUTPUT_DIR / f"{name}_noise.flac"

        print(f"  Writing {wav_path}")
        save_wav(wav_path, stereo, bit_depth=24)

        print(f"  Writing {flac_path}")
        save_flac(flac_path, stereo, bit_depth=24)

        # Also save mono versions
        mono_wav = OUTPUT_DIR / f"{name}_noise_mono.wav"
        mono_flac = OUTPUT_DIR / f"{name}_noise_mono.flac"

        print(f"  Writing {mono_wav}")
        save_wav(mono_wav, mono, bit_depth=24)

        print(f"  Writing {mono_flac}")
        save_flac(mono_flac, mono, bit_depth=24)

    print("\nDone. Files saved to:", OUTPUT_DIR)


if __name__ == "__main__":
    main()
