from __future__ import annotations

import numpy as np

from noise.utils import SAMPLE_RATE


def generate_white_noise(
    n_samples: int,
    n_channels: int = 2,
    *,
    rng: np.random.Generator | None = None,
) -> np.ndarray:
    """White noise: flat power spectrum across all frequencies.

    Args:
        n_samples: Number of audio samples to generate.
        n_channels: Number of channels (1=mono, 2=stereo).
        rng: Optional numpy random generator for reproducibility.

    Returns:
        Float32 array of shape (n_samples, n_channels) with values in [-1, 1].
    """
    if rng is None:
        rng = np.random.default_rng()
    if n_samples <= 0:
        raise ValueError(f"n_samples must be > 0, got {n_samples}")
    if n_channels not in (1, 2):
        raise ValueError(f"n_channels must be 1 or 2, got {n_channels}")
    return rng.uniform(-1.0, 1.0, (n_samples, n_channels)).astype(np.float32)


def generate_pink_noise(
    n_samples: int,
    n_channels: int = 2,
    *,
    rng: np.random.Generator | None = None,
) -> np.ndarray:
    """Pink noise (1/f): power decreases 3 dB per octave.

    Generated via frequency-domain filtering: FFT of white noise
    multiplied by a 1/sqrt(f) filter, then inverse FFT.

    Args:
        n_samples: Number of audio samples to generate.
        n_channels: Number of channels (1=mono, 2=stereo).
        rng: Optional numpy random generator for reproducibility.

    Returns:
        Float32 array of shape (n_samples, n_channels) normalized to [-1, 1].
    """
    if rng is None:
        rng = np.random.default_rng()
    if n_samples <= 0:
        raise ValueError(f"n_samples must be > 0, got {n_samples}")
    if n_channels not in (1, 2):
        raise ValueError(f"n_channels must be 1 or 2, got {n_channels}")

    white = rng.uniform(-1.0, 1.0, (n_samples, n_channels)).astype(np.float64)

    freq = np.fft.rfftfreq(n_samples, d=1.0 / SAMPLE_RATE)
    freq[0] = freq[1]
    pink_filter = 1.0 / np.sqrt(freq)

    pink = np.empty_like(white)
    for ch in range(n_channels):
        fft = np.fft.rfft(white[:, ch])
        fft *= pink_filter
        pink[:, ch] = np.fft.irfft(fft, n=n_samples)

    max_val = np.max(np.abs(pink))
    if max_val > 0:
        pink /= max_val
    return pink.astype(np.float32)


def generate_brown_noise(
    n_samples: int,
    n_channels: int = 2,
    *,
    rng: np.random.Generator | None = None,
) -> np.ndarray:
    """Brown noise (1/f^2): power decreases 6 dB per octave.

    Generated by cumulative sum (integration) of white noise.

    Args:
        n_samples: Number of audio samples to generate.
        n_channels: Number of channels (1=mono, 2=stereo).
        rng: Optional numpy random generator for reproducibility.

    Returns:
        Float32 array of shape (n_samples, n_channels) normalized to [-1, 1].
    """
    if rng is None:
        rng = np.random.default_rng()
    if n_samples <= 0:
        raise ValueError(f"n_samples must be > 0, got {n_samples}")
    if n_channels not in (1, 2):
        raise ValueError(f"n_channels must be 1 or 2, got {n_channels}")

    white = rng.uniform(-0.1, 0.1, (n_samples, n_channels)).astype(np.float64)
    brown = np.cumsum(white, axis=0)

    max_val = np.max(np.abs(brown))
    if max_val > 0:
        brown /= max_val
    return brown.astype(np.float32)


def generate_blue_noise(
    n_samples: int,
    n_channels: int = 2,
    *,
    rng: np.random.Generator | None = None,
) -> np.ndarray:
    """Blue noise (1/f^0.5): power increases 3 dB per octave.

    Generated via frequency-domain filtering: FFT of white noise
    multiplied by a sqrt(f) filter, then inverse FFT.

    Args:
        n_samples: Number of audio samples to generate.
        n_channels: Number of channels (1=mono, 2=stereo).
        rng: Optional numpy random generator for reproducibility.

    Returns:
        Float32 array of shape (n_samples, n_channels) normalized to [-1, 1].
    """
    if rng is None:
        rng = np.random.default_rng()
    if n_samples <= 0:
        raise ValueError(f"n_samples must be > 0, got {n_samples}")
    if n_channels not in (1, 2):
        raise ValueError(f"n_channels must be 1 or 2, got {n_channels}")

    white = rng.uniform(-1.0, 1.0, (n_samples, n_channels)).astype(np.float64)

    freq = np.fft.rfftfreq(n_samples, d=1.0 / SAMPLE_RATE)
    freq[0] = freq[1]
    blue_filter = np.sqrt(freq)

    blue = np.empty_like(white)
    for ch in range(n_channels):
        fft = np.fft.rfft(white[:, ch])
        fft *= blue_filter
        blue[:, ch] = np.fft.irfft(fft, n=n_samples)

    max_val = np.max(np.abs(blue))
    if max_val > 0:
        blue /= max_val
    return blue.astype(np.float32)


def generate_violet_noise(
    n_samples: int,
    n_channels: int = 2,
    *,
    rng: np.random.Generator | None = None,
) -> np.ndarray:
    """Violet noise (1/f^1): power increases 6 dB per octave.

    Generated via frequency-domain filtering: FFT of white noise
    multiplied by a f filter, then inverse FFT.

    Args:
        n_samples: Number of audio samples to generate.
        n_channels: Number of channels (1=mono, 2=stereo).
        rng: Optional numpy random generator for reproducibility.

    Returns:
        Float32 array of shape (n_samples, n_channels) normalized to [-1, 1].
    """
    if rng is None:
        rng = np.random.default_rng()
    if n_samples <= 0:
        raise ValueError(f"n_samples must be > 0, got {n_samples}")
    if n_channels not in (1, 2):
        raise ValueError(f"n_channels must be 1 or 2, got {n_channels}")

    white = rng.uniform(-1.0, 1.0, (n_samples, n_channels)).astype(np.float64)

    freq = np.fft.rfftfreq(n_samples, d=1.0 / SAMPLE_RATE)
    freq[0] = freq[1]
    violet_filter = freq

    violet = np.empty_like(white)
    for ch in range(n_channels):
        fft = np.fft.rfft(white[:, ch])
        fft *= violet_filter
        violet[:, ch] = np.fft.irfft(fft, n=n_samples)

    max_val = np.max(np.abs(violet))
    if max_val > 0:
        violet /= max_val
    return violet.astype(np.float32)


def generate_grey_noise(
    n_samples: int,
    n_channels: int = 2,
    *,
    rng: np.random.Generator | None = None,
) -> np.ndarray:
    """Grey noise: psychoacoustic equal-loudness noise.

    Generated via frequency-domain filtering: FFT of white noise
    multiplied by a 1/(1+(f/2000)^2) filter, then inverse FFT.

    Args:
        n_samples: Number of audio samples to generate.
        n_channels: Number of channels (1=mono, 2=stereo).
        rng: Optional numpy random generator for reproducibility.

    Returns:
        Float32 array of shape (n_samples, n_channels) normalized to [-1, 1].
    """
    if rng is None:
        rng = np.random.default_rng()
    if n_samples <= 0:
        raise ValueError(f"n_samples must be > 0, got {n_samples}")
    if n_channels not in (1, 2):
        raise ValueError(f"n_channels must be 1 or 2, got {n_channels}")

    white = rng.uniform(-1.0, 1.0, (n_samples, n_channels)).astype(np.float64)

    freq = np.fft.rfftfreq(n_samples, d=1.0 / SAMPLE_RATE)
    freq[0] = freq[1]
    grey_filter = 1.0 / (1.0 + (freq / 2000.0) ** 2)

    grey = np.empty_like(white)
    for ch in range(n_channels):
        fft = np.fft.rfft(white[:, ch])
        fft *= grey_filter
        grey[:, ch] = np.fft.irfft(fft, n=n_samples)

    max_val = np.max(np.abs(grey))
    if max_val > 0:
        grey /= max_val
    return grey.astype(np.float32)
